import { NextResponse } from 'next/server'
import type { ProfileData } from '@/types/profile'

// Mock profile data for testing
export async function GET() {
  const mockProfile: ProfileData = {
    summoner: {
      puuid: 'test-puuid-12345',
      gameName: 'TestSummoner',
      tagLine: 'TEST',
      profileIconId: 4568,
      summonerLevel: 420,
      lastUpdated: new Date().toISOString(),
    },
    summary: {
      totalGames: 150,
      wins: 82,
      losses: 68,
      totalKills: 1250,
      totalDeaths: 980,
      totalAssists: 1820,
      kda: 3.14,
      winrate: 54.67,
      averagePigScore: 7.8,
      longestWinStreak: 58, // Test 50+ winstreak effects
      mostPlayedChampion: 'Lux',
    },
    champions: [
      {
        championName: 'Lux',
        games: 45,
        wins: 28,
        losses: 17,
        kills: 380,
        deaths: 270,
        assists: 620,
        totalDamage: 1250000,
        averagePigScore: 8.2,
      },
      {
        championName: 'Jinx',
        games: 32,
        wins: 18,
        losses: 14,
        kills: 310,
        deaths: 240,
        assists: 420,
        totalDamage: 1150000,
        averagePigScore: 7.5,
      },
      {
        championName: 'Thresh',
        games: 28,
        wins: 15,
        losses: 13,
        kills: 180,
        deaths: 210,
        assists: 580,
        totalDamage: 680000,
        averagePigScore: 7.9,
      },
      {
        championName: 'Ezreal',
        games: 25,
        wins: 14,
        losses: 11,
        kills: 250,
        deaths: 180,
        assists: 310,
        totalDamage: 980000,
        averagePigScore: 7.2,
      },
      {
        championName: 'Sona',
        games: 20,
        wins: 7,
        losses: 13,
        kills: 130,
        deaths: 80,
        assists: 390,
        totalDamage: 420000,
        averagePigScore: 6.8,
      },
    ],
    matches: [
      {
        metadata: {
          matchId: 'TEST_1',
          participants: [
            'test-puuid-12345',
            ...Array.from({ length: 9 }, (_, i) => `dummy-${i}`),
          ],
        },
        info: {
          gameCreation: Date.now() - 3600000,
          gameDuration: 1250,
          gameEndTimestamp: Date.now() - 2350000,
          gameMode: 'ARAM',
          gameVersion: '15.1.123456',
          queueId: 450,
          participants: [
            {
              puuid: 'test-puuid-12345',
              riotIdGameName: 'TestSummoner',
              riotIdTagline: 'TEST',
              summonerName: 'TestSummoner',
              championName: 'Lux',
              championId: 99,
              kills: 12,
              deaths: 4,
              assists: 18,
              win: true,
              totalDamageDealtToChampions: 45000,
              totalDamageTaken: 28000,
              totalHeal: 15000,
              totalHealsOnTeammates: 8000,
              totalDamageShieldedOnTeammates: 3000,
              timeCCingOthers: 45,
              item0: 3157,
              item1: 3020,
              item2: 3089,
              item3: 3135,
              item4: 3916,
              item5: 3165,
              item6: 3364,
              summoner1Id: 4,
              summoner2Id: 14,
              perks: {
                statPerks: { defense: 5001, flex: 5008, offense: 5005 },
                styles: [
                  {
                    style: 8200,
                    selections: [
                      { perk: 8214 },
                      { perk: 8226 },
                      { perk: 8210 },
                      { perk: 8237 },
                    ],
                  },
                  {
                    style: 8100,
                    selections: [
                      { perk: 8126 },
                      { perk: 8106 },
                    ],
                  },
                ],
              },
              teamId: 100,
              gameEndedInEarlySurrender: false,
              champLevel: 18,
              goldEarned: 12500,
              totalMinionsKilled: 0,
              neutralMinionsKilled: 0,
              pigScore: 8.5,
            },
            // Add 9 more dummy participants for team
            ...Array.from({ length: 9 }, (_, i) => ({
              puuid: `dummy-${i}`,
              riotIdGameName: `Player${i + 1}`,
              riotIdTagline: `TAG${i}`,
              summonerName: `Player${i + 1}`,
              championName: ['Jinx', 'Thresh', 'Ezreal', 'Sona', 'MissFortune', 'Leona', 'Jhin', 'Nautilus', 'Ashe'][i],
              championId: 200 + i,
              kills: Math.floor(Math.random() * 15),
              deaths: Math.floor(Math.random() * 10),
              assists: Math.floor(Math.random() * 20),
              win: i < 4, // First 5 total (including main) win
              totalDamageDealtToChampions: Math.floor(Math.random() * 50000),
              totalDamageTaken: Math.floor(Math.random() * 30000),
              totalHeal: Math.floor(Math.random() * 10000),
              totalHealsOnTeammates: Math.floor(Math.random() * 5000),
              totalDamageShieldedOnTeammates: Math.floor(Math.random() * 3000),
              timeCCingOthers: Math.floor(Math.random() * 60),
              item0: 3157,
              item1: 3020,
              item2: 3089,
              item3: 3135,
              item4: 3916,
              item5: 3165,
              item6: 3364,
              summoner1Id: 4,
              summoner2Id: 14,
              perks: {
                statPerks: { defense: 5001, flex: 5008, offense: 5005 },
                styles: [
                  {
                    style: 8200,
                    selections: [
                      { perk: 8214 },
                      { perk: 8226 },
                      { perk: 8210 },
                      { perk: 8237 },
                    ],
                  },
                  {
                    style: 8100,
                    selections: [
                      { perk: 8126 },
                      { perk: 8106 },
                    ],
                  },
                ],
              },
              teamId: i < 4 ? 100 : 200,
              gameEndedInEarlySurrender: false,
              champLevel: Math.floor(Math.random() * 5) + 14,
              goldEarned: Math.floor(Math.random() * 5000) + 8000,
              totalMinionsKilled: 0,
              neutralMinionsKilled: 0,
              pigScore: Math.random() * 10,
            })),
          ],
        },
      },
    ],
    recentlyPlayedWith: [
      {
        puuid: 'friend-1',
        gameName: 'BestFriend',
        tagLine: 'BFF',
        games: 15,
        wins: 9,
        losses: 6,
        profileIconId: 1234,
      },
      {
        puuid: 'friend-2',
        gameName: 'Teammate',
        tagLine: 'DUO',
        games: 8,
        wins: 5,
        losses: 3,
        profileIconId: 5678,
      },
    ],
    updateStatus: {
      hasActiveJob: false,
      cooldownUntil: null,
    },
  }

  return NextResponse.json(mockProfile)
}
